List<String> educationAndAcademics = [
  "Education",
  "School",
  "Student",
  "Teacher",
  "Classroom",
  "Lesson",
  "Subject",
  "Homework",
  "Assignment",
  "Exam",
  "Test",
  "Grade",
  "Report Card",
  "Attendance",
  "Textbook",
  "Notebook",
  "Pencil",
  "Pen",
  "Calculator",
  "Science",
  "Mathematics",
  "History",
  "Geography",
  "English",
  "Literature",
  "Language",
  "Art",
  "Music",
  "Physical Education",
  "Computer Science",
  "Biology",
  "Chemistry",
  "Physics",
  "Economics",
  "Sociology",
  "Psychology",
  "Philosophy",
  "Research",
  "Study",
  "Learning",
  "Knowledge",
  "Academic",
  "Degree",
  "Diploma",
  "Graduation",
  "University",
  "College",
  "Professor",
  "Campus",
  "Library",
  "Lecture",
  "Seminar",
  "Scholarship",
  "Academic Achievement",
  "Extracurricular Activities",
];
