class Families {
  static List<String> families() {
    return [
      "Family",
      "Mother",
      "Father",
      "Parents",
      "Sibling",
      "Brother",
      "Sister",
      "Son",
      "Daughter",
      "Grandparents",
      "Grandfather",
      "Grandmother",
      "Cousin",
      "Uncle",
      "Aunt",
      "Nephew",
      "Niece",
      "Spouse",
      "Husband",
      "Wife",
      "Partner",
      "Boyfriend",
      "Girlfriend",
      "Fiancé",
      "Fiancée",
      "Marriage",
      "Divorce",
      "Single",
      "Engaged",
      "Wedding",
      "Love",
      "Affection",
      "Relationship",
      "Friendship",
      "Relatives",
      "In-laws",
      "Orphan",
      "Adopted",
      "Stepfamily",
      "Family Tree",
      "Ancestors",
      "Descendants",
    ];
  }
}
