class Numbers {
  List<Map<String, String>> get chinese => [
        {"Number": "0", "Pronunciation": "líng"},
        {"Number": "1", "Pronunciation": "yī"},
        {"Number": "2", "Pronunciation": "èr"},
        {"Number": "3", "Pronunciation": "sān"},
        {"Number": "4", "Pronunciation": "sì"},
        {"Number": "5", "Pronunciation": "wǔ"},
        {"Number": "6", "Pronunciation": "liù"},
        {"Number": "7", "Pronunciation": "qī"},
        {"Number": "8", "Pronunciation": "bā"},
        {"Number": "9", "Pronunciation": "jiǔ"},
        {"Number": "10", "Pronunciation": "shí"},
        {"Number": "11", "Pronunciation": "shí yī"},
        {"Number": "12", "Pronunciation": "shí èr"},
        {"Number": "13", "Pronunciation": "shí sān"},
        {"Number": "14", "Pronunciation": "shí sì"},
        {"Number": "15", "Pronunciation": "shí wǔ"},
        {"Number": "16", "Pronunciation": "shí liù"},
        {"Number": "17", "Pronunciation": "shí qī"},
        {"Number": "18", "Pronunciation": "shí bā"},
        {"Number": "19", "Pronunciation": "shí jiǔ"},
        {"Number": "20", "Pronunciation": "èr shí"},
        {"Number": "21", "Pronunciation": "èr shí yī"},
        {"Number": "22", "Pronunciation": "èr shí èr"},
        {"Number": "23", "Pronunciation": "èr shí sān"},
        {"Number": "24", "Pronunciation": "èr shí sì"},
        {"Number": "25", "Pronunciation": "èr shí wǔ"},
        {"Number": "26", "Pronunciation": "èr shí liù"},
        {"Number": "27", "Pronunciation": "èr shí qī"},
        {"Number": "28", "Pronunciation": "èr shí bā"},
        {"Number": "29", "Pronunciation": "èr shí jiǔ"},
        {"Number": "30", "Pronunciation": "sān shí"},
        {"Number": "40", "Pronunciation": "sì shí"},
        {"Number": "50", "Pronunciation": "wǔ shí"},
        {"Number": "60", "Pronunciation": "liù shí"},
        {"Number": "70", "Pronunciation": "qī shí"},
        {"Number": "80", "Pronunciation": "bā shí"},
        {"Number": "90", "Pronunciation": "jiǔ shí"},
        {"Number": "100", "Pronunciation": "yī bǎi"},
        {"Number": "1000", "Pronunciation": "yī qiān"},
        {"Number": "2000", "Pronunciation": "liǎng qiān"},
        {"Number": "3000", "Pronunciation": "sān qiān"},
        {"Number": "100000", "Pronunciation": "yī wàn"},
        {"Number": "1000000", "Pronunciation": "yī bǎi wàn"},
        {"Number": "2000000", "Pronunciation": "liǎng bǎi wàn"},
      ];

  List<Map<String, String>> get french => [
        {"Number": "0", "Pronunciation": "zéro"},
        {"Number": "1", "Pronunciation": "un"},
        {"Number": "2", "Pronunciation": "deux"},
        {"Number": "3", "Pronunciation": "trois"},
        {"Number": "4", "Pronunciation": "quatre"},
        {"Number": "5", "Pronunciation": "cinq"},
        {"Number": "6", "Pronunciation": "six"},
        {"Number": "7", "Pronunciation": "sept"},
        {"Number": "8", "Pronunciation": "huit"},
        {"Number": "9", "Pronunciation": "neuf"},
        {"Number": "10", "Pronunciation": "dix"},
        {"Number": "11", "Pronunciation": "onze"},
        {"Number": "12", "Pronunciation": "douze"},
        {"Number": "13", "Pronunciation": "treize"},
        {"Number": "14", "Pronunciation": "quatorze"},
        {"Number": "15", "Pronunciation": "quinze"},
        {"Number": "16", "Pronunciation": "seize"},
        {"Number": "17", "Pronunciation": "dix-sept"},
        {"Number": "18", "Pronunciation": "dix-huit"},
        {"Number": "19", "Pronunciation": "dix-neuf"},
        {"Number": "20", "Pronunciation": "vingt"},
        {"Number": "21", "Pronunciation": "vingt et un"},
        {"Number": "22", "Pronunciation": "vingt-deux"},
        {"Number": "23", "Pronunciation": "vingt-trois"},
        {"Number": "24", "Pronunciation": "vingt-quatre"},
        {"Number": "25", "Pronunciation": "vingt-cinq"},
        {"Number": "26", "Pronunciation": "vingt-six"},
        {"Number": "27", "Pronunciation": "vingt-sept"},
        {"Number": "28", "Pronunciation": "vingt-huit"},
        {"Number": "29", "Pronunciation": "vingt-neuf"},
        {"Number": "30", "Pronunciation": "trente"},
        {"Number": "40", "Pronunciation": "quarante"},
        {"Number": "50", "Pronunciation": "cinquante"},
        {"Number": "60", "Pronunciation": "soixante"},
        {"Number": "70", "Pronunciation": "soixante-dix"},
        {"Number": "80", "Pronunciation": "quatre-vingts"},
        {"Number": "90", "Pronunciation": "quatre-vingt-dix"},
        {"Number": "100", "Pronunciation": "cent"},
        {"Number": "1000", "Pronunciation": "mille"},
        {"Number": "2000", "Pronunciation": "deux mille"},
        {"Number": "3000", "Pronunciation": "trois mille"},
        {"Number": "100000", "Pronunciation": "cent mille"},
        {"Number": "1000000", "Pronunciation": "un million"},
        {"Number": "2000000", "Pronunciation": "deux millions"},
      ];

  List<Map<String, String>> get germany => [
        {"Number": "0", "Pronunciation": "null"},
        {"Number": "1", "Pronunciation": "eins"},
        {"Number": "2", "Pronunciation": "zwei"},
        {"Number": "3", "Pronunciation": "drei"},
        {"Number": "4", "Pronunciation": "vier"},
        {"Number": "5", "Pronunciation": "fünf"},
        {"Number": "6", "Pronunciation": "sechs"},
        {"Number": "7", "Pronunciation": "sieben"},
        {"Number": "8", "Pronunciation": "acht"},
        {"Number": "9", "Pronunciation": "neun"},
        {"Number": "10", "Pronunciation": "zehn"},
        {"Number": "11", "Pronunciation": "elf"},
        {"Number": "12", "Pronunciation": "zwölf"},
        {"Number": "13", "Pronunciation": "dreizehn"},
        {"Number": "14", "Pronunciation": "vierzehn"},
        {"Number": "15", "Pronunciation": "fünfzehn"},
        {"Number": "16", "Pronunciation": "sechzehn"},
        {"Number": "17", "Pronunciation": "siebzehn"},
        {"Number": "18", "Pronunciation": "achtzehn"},
        {"Number": "19", "Pronunciation": "neunzehn"},
        {"Number": "20", "Pronunciation": "zwanzig"},
        {"Number": "21", "Pronunciation": "einundzwanzig"},
        {"Number": "22", "Pronunciation": "zweiundzwanzig"},
        {"Number": "23", "Pronunciation": "dreiundzwanzig"},
        {"Number": "24", "Pronunciation": "vierundzwanzig"},
        {"Number": "25", "Pronunciation": "fünfundzwanzig"},
        {"Number": "26", "Pronunciation": "sechsundzwanzig"},
        {"Number": "27", "Pronunciation": "siebenundzwanzig"},
        {"Number": "28", "Pronunciation": "achtundzwanzig"},
        {"Number": "29", "Pronunciation": "neunundzwanzig"},
        {"Number": "30", "Pronunciation": "dreißig"},
        {"Number": "40", "Pronunciation": "vierzig"},
        {"Number": "50", "Pronunciation": "fünfzig"},
        {"Number": "60", "Pronunciation": "sechzig"},
        {"Number": "70", "Pronunciation": "siebzig"},
        {"Number": "80", "Pronunciation": "achtzig"},
        {"Number": "90", "Pronunciation": "neunzig"},
        {"Number": "100", "Pronunciation": "einhundert"},
        {"Number": "1000", "Pronunciation": "eintausend"},
        {"Number": "2000", "Pronunciation": "zweitausend"},
        {"Number": "3000", "Pronunciation": "dreitausend"},
        {"Number": "100000", "Pronunciation": "einhunderttausend"},
        {"Number": "1000000", "Pronunciation": "eine Million"},
        {"Number": "2000000", "Pronunciation": "zwei Millionen"},
      ];

  List<Map<String, String>> get indian => [
        {"Number": "0", "Pronunciation": "शून्य (shunya)"},
        {"Number": "1", "Pronunciation": "एक (ek)"},
        {"Number": "2", "Pronunciation": "दो (do)"},
        {"Number": "3", "Pronunciation": "तीन (teen)"},
        {"Number": "4", "Pronunciation": "चार (chaar)"},
        {"Number": "5", "Pronunciation": "पांच (paanch)"},
        {"Number": "6", "Pronunciation": "छह (chhah)"},
        {"Number": "7", "Pronunciation": "सात (saat)"},
        {"Number": "8", "Pronunciation": "आठ (aath)"},
        {"Number": "9", "Pronunciation": "नौ (nau)"},
        {"Number": "10", "Pronunciation": "दस (das)"},
        {"Number": "11", "Pronunciation": "ग्यारह (gyarah)"},
        {"Number": "12", "Pronunciation": "बारह (baarah)"},
        {"Number": "13", "Pronunciation": "तेरह (terah)"},
        {"Number": "14", "Pronunciation": "चौदह (chauddah)"},
        {"Number": "15", "Pronunciation": "पंद्रह (pandrah)"},
        {"Number": "16", "Pronunciation": "सोलह (solah)"},
        {"Number": "17", "Pronunciation": "सत्रह (satrah)"},
        {"Number": "18", "Pronunciation": "अठारह (atharah)"},
        {"Number": "19", "Pronunciation": "उन्नीस (unnis)"},
        {"Number": "20", "Pronunciation": "बीस (bees)"},
        {"Number": "21", "Pronunciation": "इक्कीस (ikkis)"},
        {"Number": "22", "Pronunciation": "बाईस (baais)"},
        {"Number": "23", "Pronunciation": "तेईस (teis)"},
        {"Number": "24", "Pronunciation": "चौबीस (chaubis)"},
        {"Number": "25", "Pronunciation": "पच्चीस (pachis)"},
        {"Number": "26", "Pronunciation": "छब्बीस (chhabbis)"},
        {"Number": "27", "Pronunciation": "सत्ताईस (sattais)"},
        {"Number": "28", "Pronunciation": "अट्ठाईस (atthais)"},
        {"Number": "29", "Pronunciation": "उनतीस (unatis)"},
        {"Number": "30", "Pronunciation": "तीस (tees)"},
        {"Number": "40", "Pronunciation": "चालीस (chaalis)"},
        {"Number": "50", "Pronunciation": "पचास (pachas)"},
        {"Number": "60", "Pronunciation": "साठ (saath)"},
        {"Number": "70", "Pronunciation": "सत्तर (sattar)"},
        {"Number": "80", "Pronunciation": "अस्सी (assee)"},
        {"Number": "90", "Pronunciation": "नव्वे (nawwe)"},
        {"Number": "100", "Pronunciation": "एक सौ (ek sau)"},
        {"Number": "1000", "Pronunciation": "एक हजार (ek hazaar)"},
        {"Number": "2000", "Pronunciation": "दो हजार (do hazaar)"},
        {"Number": "3000", "Pronunciation": "तीन हजार (teen hazaar)"},
        {"Number": "100000", "Pronunciation": "एक लाख (ek lakh)"},
        {"Number": "1000000", "Pronunciation": "दस लाख (das lakh)"},
        {"Number": "2000000", "Pronunciation": "बीस लाख (bees lakh)"},
      ];

  List<Map<String, String>> get italian => [
        {"Number": "0", "Pronunciation": "zero"},
        {"Number": "1", "Pronunciation": "uno"},
        {"Number": "2", "Pronunciation": "due"},
        {"Number": "3", "Pronunciation": "tre"},
        {"Number": "4", "Pronunciation": "quattro"},
        {"Number": "5", "Pronunciation": "cinque"},
        {"Number": "6", "Pronunciation": "sei"},
        {"Number": "7", "Pronunciation": "sette"},
        {"Number": "8", "Pronunciation": "otto"},
        {"Number": "9", "Pronunciation": "nove"},
        {"Number": "10", "Pronunciation": "dieci"},
        {"Number": "11", "Pronunciation": "undici"},
        {"Number": "12", "Pronunciation": "dodici"},
        {"Number": "13", "Pronunciation": "tredici"},
        {"Number": "14", "Pronunciation": "quattordici"},
        {"Number": "15", "Pronunciation": "quindici"},
        {"Number": "16", "Pronunciation": "sedici"},
        {"Number": "17", "Pronunciation": "diciassette"},
        {"Number": "18", "Pronunciation": "diciotto"},
        {"Number": "19", "Pronunciation": "diciannove"},
        {"Number": "20", "Pronunciation": "venti"},
        {"Number": "21", "Pronunciation": "ventuno"},
        {"Number": "22", "Pronunciation": "ventidue"},
        {"Number": "23", "Pronunciation": "ventitré"},
        {"Number": "24", "Pronunciation": "ventiquattro"},
        {"Number": "25", "Pronunciation": "venticinque"},
        {"Number": "26", "Pronunciation": "ventisei"},
        {"Number": "27", "Pronunciation": "ventisette"},
        {"Number": "28", "Pronunciation": "ventotto"},
        {"Number": "29", "Pronunciation": "ventinove"},
        {"Number": "30", "Pronunciation": "trenta"},
        {"Number": "40", "Pronunciation": "quaranta"},
        {"Number": "50", "Pronunciation": "cinquanta"},
        {"Number": "60", "Pronunciation": "sessanta"},
        {"Number": "70", "Pronunciation": "settanta"},
        {"Number": "80", "Pronunciation": "ottanta"},
        {"Number": "90", "Pronunciation": "novanta"},
        {"Number": "100", "Pronunciation": "cento"},
        {"Number": "1000", "Pronunciation": "mille"},
        {"Number": "2000", "Pronunciation": "duemila"},
        {"Number": "3000", "Pronunciation": "tremila"},
        {"Number": "100000", "Pronunciation": "centomila"},
        {"Number": "1000000", "Pronunciation": "un milione"},
        {"Number": "2000000", "Pronunciation": "due milioni"},
      ];

  List<Map<String, String>> get japanese => [
        {"Number": "0", "Pronunciation": "ゼロ (zero)"},
        {"Number": "1", "Pronunciation": "いち (ichi)"},
        {"Number": "2", "Pronunciation": "に (ni)"},
        {"Number": "3", "Pronunciation": "さん (san)"},
        {"Number": "4", "Pronunciation": "よん (yon)"},
        {"Number": "5", "Pronunciation": "ご (go)"},
        {"Number": "6", "Pronunciation": "ろく (roku)"},
        {"Number": "7", "Pronunciation": "なな (nana)"},
        {"Number": "8", "Pronunciation": "はち (hachi)"},
        {"Number": "9", "Pronunciation": "きゅう (kyuu)"},
        {"Number": "10", "Pronunciation": "じゅう (juu)"},
        {"Number": "11", "Pronunciation": "じゅういち (juuichi)"},
        {"Number": "12", "Pronunciation": "じゅうに (juuni)"},
        {"Number": "13", "Pronunciation": "じゅうさん (juusan)"},
        {"Number": "14", "Pronunciation": "じゅうよん (juuyon)"},
        {"Number": "15", "Pronunciation": "じゅうご (juugo)"},
        {"Number": "16", "Pronunciation": "じゅうろく (juuroku)"},
        {"Number": "17", "Pronunciation": "じゅうしち (juushichi)"},
        {"Number": "18", "Pronunciation": "じゅうはち (juuhachi)"},
        {"Number": "19", "Pronunciation": "じゅうきゅう (juukyuu)"},
        {"Number": "20", "Pronunciation": "にじゅう (nijuu)"},
        {"Number": "21", "Pronunciation": "にじゅういち (nijuui)"},
        {"Number": "22", "Pronunciation": "にじゅうに (nijuuni)"},
        {"Number": "23", "Pronunciation": "にじゅうさん (nijuusan)"},
        {"Number": "24", "Pronunciation": "にじゅうよん (nijuuyon)"},
        {"Number": "25", "Pronunciation": "にじゅうご (nijuugo)"},
        {"Number": "26", "Pronunciation": "にじゅうろく (nijuuroku)"},
        {"Number": "27", "Pronunciation": "にじゅうしち (nijuushichi)"},
        {"Number": "28", "Pronunciation": "にじゅうはち (nijuuhachi)"},
        {"Number": "29", "Pronunciation": "にじゅうきゅう (nijuukyuu)"},
        {"Number": "30", "Pronunciation": "さんじゅう (sanjuu)"},
        {"Number": "40", "Pronunciation": "よんじゅう (yonjuu)"},
        {"Number": "50", "Pronunciation": "ごじゅう (gojuu)"},
        {"Number": "60", "Pronunciation": "ろくじゅう (rokujuu)"},
        {"Number": "70", "Pronunciation": "ななじゅう (nanajuu)"},
        {"Number": "80", "Pronunciation": "はちじゅう (hachijuu)"},
        {"Number": "90", "Pronunciation": "きゅうじゅう (kyuujuu)"},
        {"Number": "100", "Pronunciation": "ひゃく (hyaku)"},
        {"Number": "1000", "Pronunciation": "せん (sen)"},
        {"Number": "2000", "Pronunciation": "にせん (nisen)"},
        {"Number": "3000", "Pronunciation": "さんぜん (sanzen)"},
        {"Number": "10000", "Pronunciation": "いちまん (ichiman)"},
        {"Number": "100000", "Pronunciation": "じゅうまん (juuman)"},
        {"Number": "1000000", "Pronunciation": "ひゃくまん (hyakuman)"},
        {"Number": "100000000", "Pronunciation": "いちおく (ichioku)"},
        {"Number": "1000000000", "Pronunciation": "じゅうおく (juuoku)"},
      ];

  List<Map<String, String>> get russian => [
        {"Number": "0", "Pronunciation": "ноль (nol')"},
        {"Number": "1", "Pronunciation": "один (odin)"},
        {"Number": "2", "Pronunciation": "два (dva)"},
        {"Number": "3", "Pronunciation": "три (tri)"},
        {"Number": "4", "Pronunciation": "четыре (chetyre)"},
        {"Number": "5", "Pronunciation": "пять (pyat')"},
        {"Number": "6", "Pronunciation": "шесть (shest')"},
        {"Number": "7", "Pronunciation": "семь (sem')"},
        {"Number": "8", "Pronunciation": "восемь (vosem')"},
        {"Number": "9", "Pronunciation": "девять (devyat')"},
        {"Number": "10", "Pronunciation": "десять (desyat')"},
        {"Number": "11", "Pronunciation": "одиннадцать (odinnadtsat')"},
        {"Number": "12", "Pronunciation": "двенадцать (dvenadtsat')"},
        {"Number": "13", "Pronunciation": "тринадцать (trinadtsat')"},
        {"Number": "14", "Pronunciation": "четырнадцать (chetyrnadtsat')"},
        {"Number": "15", "Pronunciation": "пятнадцать (pyatnadtsat')"},
        {"Number": "16", "Pronunciation": "шестнадцать (shestnadtsat')"},
        {"Number": "17", "Pronunciation": "семнадцать (semnadtsat')"},
        {"Number": "18", "Pronunciation": "восемнадцать (vosemnadtsat')"},
        {"Number": "19", "Pronunciation": "девятнадцать (devyatnadtsat')"},
        {"Number": "20", "Pronunciation": "двадцать (dvadtsat')"},
        {"Number": "21", "Pronunciation": "двадцать один (dvadtsat' odin)"},
        {"Number": "22", "Pronunciation": "двадцать два (dvadtsat' dva)"},
        {"Number": "23", "Pronunciation": "двадцать три (dvadtsat' tri)"},
        {
          "Number": "24",
          "Pronunciation": "двадцать четыре (dvadtsat' chetyre)"
        },
        {"Number": "25", "Pronunciation": "двадцать пять (dvadtsat' pyat')"},
        {"Number": "26", "Pronunciation": "двадцать шесть (dvadtsat' shest')"},
        {"Number": "27", "Pronunciation": "двадцать семь (dvadtsat' sem')"},
        {"Number": "28", "Pronunciation": "двадцать восемь (dvadtsat' vosem')"},
        {
          "Number": "29",
          "Pronunciation": "двадцать девять (dvadtsat' devyat')"
        },
        {"Number": "30", "Pronunciation": "тридцать (tridtsat')"},
        {"Number": "40", "Pronunciation": "сорок (sorok)"},
        {"Number": "50", "Pronunciation": "пятьдесят (pyat'desyat')"},
        {"Number": "60", "Pronunciation": "шестьдесят (shest'desyat')"},
        {"Number": "70", "Pronunciation": "семьдесят (sem'desyat')"},
        {"Number": "80", "Pronunciation": "восемьдесят (vosem'desyat')"},
        {"Number": "90", "Pronunciation": "девяносто (devyanosto)"},
        {"Number": "100", "Pronunciation": "сто (sto)"},
        {"Number": "1000", "Pronunciation": "тысяча (tyisyacha)"},
        {"Number": "2000", "Pronunciation": "две тысячи (dve tyisyachi)"},
        {"Number": "3000", "Pronunciation": "три тысячи (tri tyisyachi)"},
        {"Number": "10000", "Pronunciation": "десять тысяч (desyat' tyisyach)"},
        {"Number": "100000", "Pronunciation": "сто тысяч (sto tyisyach)"},
        {"Number": "1000000", "Pronunciation": "миллион (million)"},
        {"Number": "1000000000", "Pronunciation": "миллиард (milliard)"},
      ];

  List<Map<String, String>> get arabic => [
        {"Number": "0", "Pronunciation": "صفر (sifr)"},
        {"Number": "1", "Pronunciation": "واحد (wahid)"},
        {"Number": "2", "Pronunciation": "اثنان (ithnan)"},
        {"Number": "3", "Pronunciation": "ثلاثة (thalatha)"},
        {"Number": "4", "Pronunciation": "أربعة (arba'a)"},
        {"Number": "5", "Pronunciation": "خمسة (khamsa)"},
        {"Number": "6", "Pronunciation": "ستة (sitta)"},
        {"Number": "7", "Pronunciation": "سبعة (sab'a)"},
        {"Number": "8", "Pronunciation": "ثمانية (thamaniya)"},
        {"Number": "9", "Pronunciation": "تسعة (tis'a)"},
        {"Number": "10", "Pronunciation": "عشرة (ashara)"},
        {"Number": "11", "Pronunciation": "أحد عشر (ahad 'ashar)"},
        {"Number": "12", "Pronunciation": "اثنا عشر (ithnan 'ashar)"},
        {"Number": "13", "Pronunciation": "ثلاثة عشر (thalatha 'ashar)"},
        {"Number": "14", "Pronunciation": "أربعة عشر (arba'a 'ashar)"},
        {"Number": "15", "Pronunciation": "خمسة عشر (khamsa 'ashar)"},
        {"Number": "16", "Pronunciation": "ستة عشر (sitta 'ashar)"},
        {"Number": "17", "Pronunciation": "سبعة عشر (sab'a 'ashar)"},
        {"Number": "18", "Pronunciation": "ثمانية عشر (thamaniya 'ashar)"},
        {"Number": "19", "Pronunciation": "تسعة عشر (tis'a 'ashar)"},
        {"Number": "20", "Pronunciation": "عشرون (ishrun)"},
        {"Number": "21", "Pronunciation": "واحد وعشرون (wahid wa'ishrun)"},
        {"Number": "22", "Pronunciation": "اثنان وعشرون (ithnan wa'ishrun)"},
        {"Number": "23", "Pronunciation": "ثلاثة وعشرون (thalatha wa'ishrun)"},
        {"Number": "24", "Pronunciation": "أربعة وعشرون (arba'a wa'ishrun)"},
        {"Number": "25", "Pronunciation": "خمسة وعشرون (khamsa wa'ishrun)"},
        {"Number": "26", "Pronunciation": "ستة وعشرون (sitta wa'ishrun)"},
        {"Number": "27", "Pronunciation": "سبعة وعشرون (sab'a wa'ishrun)"},
        {
          "Number": "28",
          "Pronunciation": "ثمانية وعشرون (thamaniya wa'ishrun)"
        },
        {"Number": "29", "Pronunciation": "تسعة وعشرون (tis'a wa'ishrun)"},
        {"Number": "30", "Pronunciation": "ثلاثون (thalathun)"},
        {"Number": "40", "Pronunciation": "أربعون (arba'un)"},
        {"Number": "50", "Pronunciation": "خمسون (khamsun)"},
        {"Number": "60", "Pronunciation": "ستون (sittun)"},
        {"Number": "70", "Pronunciation": "سبعون (sab'un)"},
        {"Number": "80", "Pronunciation": "ثمانون (thamanun)"},
        {"Number": "90", "Pronunciation": "تسعون (tis'un)"},
        {"Number": "100", "Pronunciation": "مئة (mi'a)"},
        {"Number": "1000", "Pronunciation": "ألف (alf)"},
        {"Number": "2000", "Pronunciation": "ألفين (alfein)"},
        {"Number": "3000", "Pronunciation": "ثلاثة آلاف (thalathat 'alaaf)"},
        {"Number": "10000", "Pronunciation": "عشرة آلاف (asharat 'alaaf)"},
        {"Number": "100000", "Pronunciation": "مئة ألف (mi'a 'alf)"},
        {"Number": "1000000", "Pronunciation": "مليون (milyun)"},
        {"Number": "1000000000", "Pronunciation": "مليار (milyar)"},
      ];

  List<Map<String, String>> get spanish => [
        {"Number": "0", "Pronunciation": "cero"},
        {"Number": "1", "Pronunciation": "uno"},
        {"Number": "2", "Pronunciation": "dos"},
        {"Number": "3", "Pronunciation": "tres"},
        {"Number": "4", "Pronunciation": "cuatro"},
        {"Number": "5", "Pronunciation": "cinco"},
        {"Number": "6", "Pronunciation": "seis"},
        {"Number": "7", "Pronunciation": "siete"},
        {"Number": "8", "Pronunciation": "ocho"},
        {"Number": "9", "Pronunciation": "nueve"},
        {"Number": "10", "Pronunciation": "diez"},
        {"Number": "11", "Pronunciation": "once"},
        {"Number": "12", "Pronunciation": "doce"},
        {"Number": "13", "Pronunciation": "trece"},
        {"Number": "14", "Pronunciation": "catorce"},
        {"Number": "15", "Pronunciation": "quince"},
        {"Number": "16", "Pronunciation": "dieciséis"},
        {"Number": "17", "Pronunciation": "diecisiete"},
        {"Number": "18", "Pronunciation": "dieciocho"},
        {"Number": "19", "Pronunciation": "diecinueve"},
        {"Number": "20", "Pronunciation": "veinte"},
        {"Number": "21", "Pronunciation": "veintiuno"},
        {"Number": "22", "Pronunciation": "veintidós"},
        {"Number": "23", "Pronunciation": "veintitrés"},
        {"Number": "24", "Pronunciation": "veinticuatro"},
        {"Number": "25", "Pronunciation": "veinticinco"},
        {"Number": "26", "Pronunciation": "veintiséis"},
        {"Number": "27", "Pronunciation": "veintisiete"},
        {"Number": "28", "Pronunciation": "veintiocho"},
        {"Number": "29", "Pronunciation": "veintinueve"},
        {"Number": "30", "Pronunciation": "treinta"},
        {"Number": "40", "Pronunciation": "cuarenta"},
        {"Number": "50", "Pronunciation": "cincuenta"},
        {"Number": "60", "Pronunciation": "sesenta"},
        {"Number": "70", "Pronunciation": "setenta"},
        {"Number": "80", "Pronunciation": "ochenta"},
        {"Number": "90", "Pronunciation": "noventa"},
        {"Number": "100", "Pronunciation": "cien"},
        {"Number": "1000", "Pronunciation": "mil"},
        {"Number": "2000", "Pronunciation": "dos mil"},
        {"Number": "3000", "Pronunciation": "tres mil"},
        {"Number": "10000", "Pronunciation": "diez mil"},
        {"Number": "100000", "Pronunciation": "cien mil"},
        {"Number": "1000000", "Pronunciation": "un millón"},
        {"Number": "1000000000", "Pronunciation": "mil millones"},
      ];
}
