List<String> workAndCareers = [
  "Work",
  "Job",
  "Career",
  "Employment",
  "Office",
  "Company",
  "Colleague",
  "Boss",
  "Employee",
  "Resume",
  "Interview",
  "Hire",
  "Fired",
  "Promotion",
  "Salary",
  "Paycheck",
  "Meeting",
  "Deadline",
  "Task",
  "Project",
  "Team",
  "Collaboration",
  "Leadership",
  "Skills",
  "Experience",
  "Qualifications",
  "Training",
  "Professional",
  "Networking",
  "Work-Life Balance",
  "Flexibility",
  "Remote Work",
  "Entrepreneur",
  "Business",
  "Start-up",
  "Success",
  "Achievement",
  "Growth",
  "Opportunity",
  "Goal",
  "Productivity",
  "Stress",
  "Workplace",
  "Ethics",
  "Dedication",
  "Career Development",
  "Job Satisfaction",
  "Workplace Culture",
  "Workplace Diversity",
];
